### ISSUE TITLE
Please support firebase analytics. (RouteSettings(name: 'HomeView'),)

### ISSUE THREAD

**Issue by peterbyCom** [mincheol-shin/transition#2]
Hello there.
transition works so perfectly. 
but it cannot be used with firebase.
Because firebase needs to know the name of the route.

https://www.filledstacks.com/post/firebase-analytics-and-metrics-in-flutter/
https://pub.dev/packages/firebase_analytics

example: 

Navigator.push(
  context,
  Transition(
     child: Page(data: Json),
transitionEffect: TransitionEffect.RIGHT_TO_LEFT),
);

compatible example:

Navigator.push(
    context,
    MaterialPageRoute(
      builder: (context) => HomeView(),
      settings: RouteSettings(name: 'HomeView'),
    ),
  );
}

**Comment by mincheol-shin** [comment]
Thank you for writing your opinion!

If possible, we will apply the function to proceed with a new update.

**Comment by mincheol-shin** [comment]
We added the function and proceeded with the [3.0.0](https://pub.dev/packages/page_route_transition) update.

Thank you.
